import type { Game } from './types';

const base = [
  ['1','Drive Mad','drive-mad','Racing','🚗','g1','HOT','Wild physics driving with ridiculous tracks and quick restarts.'],
  ['2','Mad GunZ','mad-gunz','Action','🔫','g2',null,'Fast browser battles with chunky arcade action.'],
  ['3','Neon Rush','neon-rush','Action','⚡','g3','NEW','Dash through a neon arena and chase a new high score.'],
  ['4','Crazy Bikes','crazy-bikes','Racing','🏍️','g4',null,'Balance, boost and launch through colorful stunt courses.'],
  ['5','Subway Dash','subway-dash','Adventure','🏃','g5','HOT','Run, dodge and collect rewards across busy city tracks.'],
  ['6','Goal Storm','goal-storm','Sports','⚽','g6',null,'Quick football action with easy controls and instant play.'],
  ['7','Epic Battle','epic-battle','Action','⚔️','g7',null,'Build your squad and survive fast tactical battles.'],
  ['8','Block Craft','block-craft','Casual','🧱','g8',null,'Build freely in a bright block world made for short sessions.'],
  ['9','Pocket Hoops','pocket-hoops','Sports','🏀','g9',null,'Simple basketball shots with streak-based scoring.'],
  ['10','Car Clash','car-clash','Racing','🏎️','g10','NEW','Arcade car battles with jumps, bumps and short races.'],
  ['11','Theme Hotel','theme-hotel','Girls','🏨','g11',null,'Create, decorate and manage a colorful dream hotel.'],
  ['12','Sausage Flip','sausage-flip','Casual','🌭','g12',null,'Flip through funny obstacle courses with one-touch controls.'],
  ['13','Stick Merge','stick-merge','Action','🎯','g13',null,'Merge gear and blast your way through compact action rounds.'],
  ['14','Brain Flip','brain-flip','Puzzle','🧩','g14','TRENDING','Flip, match and solve increasingly tricky visual puzzles.'],
  ['15','Sky Raiders','sky-raiders','Action','🚀','g15',null,'Arcade sky battles with fast movement and score chasing.'],
  ['16','Candy Pop','candy-pop','Casual','🍭','g16',null,'Bright, fast match-style rounds for relaxed play.'],
  ['17','Drift Zero','drift-zero','Racing','🔥','g17','HOT','Hold the drift, chain corners and beat your best run.'],
  ['18','Shadow Ninja','shadow-ninja','Adventure','🥷','g18',null,'Jump, dodge and survive a fast obstacle course.'],
  ['19','Duo Dash','duo-dash','2 Player','👥','g19','2P','A quick two-player challenge for the same screen.'],
  ['20','Island Run','island-run','Adventure','🏝️','g20',null,'Run across tropical islands, collect gems and avoid traps.'],
  ['21','Street Rider','street-rider','Racing','🛵','g21',null,'Zip through traffic and push for a longer combo.'],
  ['22','Monster Merge','monster-merge','Puzzle','👾','g22',null,'Combine strange creatures and unlock the next evolution.'],
  ['23','Mini Cricket','mini-cricket','Sports','🏏','g23',null,'Quick timing-based cricket built for browser play.'],
  ['24','Makeover Star','makeover-star','Girls','💄','g24',null,'Style, match and create fun makeover combinations.'],
  ['25','Turbo Goal','turbo-goal','Sports','🥅','g5','NEW','Fast arcade football rounds with dramatic finish shots.'],
  ['26','Pixel Arena','pixel-arena','Multiplayer','🎮','g6','HOT','Quick multiplayer-style arena rounds with arcade energy.'],
  ['27','Mystic Tiles','mystic-tiles','Puzzle','🔮','g14',null,'Match symbols and clear layered puzzle boards.'],
  ['28','City Parking','city-parking','Racing','🅿️','g2',null,'Precision parking challenges with progressively tighter spaces.'],
  ['29','Jungle Jump','jungle-jump','Adventure','🐒','g20',null,'Leap through jungle paths and collect hidden treasure.'],
  ['30','Tiny Chef','tiny-chef','Casual','👨‍🍳','g16','NEW','Serve fast orders and keep your tiny kitchen moving.'],
  ['31','Sniper Grid','sniper-grid','Shooting','🎯','g13',null,'Timing-focused shooting stages designed for quick sessions.'],
  ['32','Chess Blitz','chess-blitz','Board','♟️','g18',null,'Fast board-game inspired rounds for strategy fans.'],
] as const;

export const seedGames: Game[] = base.map((g, index) => ({
  id: `demo-${g[0]}`,
  provider: 'demo',
  providerGameId: g[0],
  title: g[1],
  slug: g[2],
  category: g[3],
  categories: [g[3]],
  tags: [g[3].toLowerCase(), 'browser', 'free'],
  emoji: g[4],
  gradient: g[5],
  badge: g[6],
  description: g[7],
  seoDescription: `${g[7]} Play ${g[1]} free in your browser on MADGAMES.FUN.`,
  instructions: 'Click Play, then use the controls shown inside the game. This seeded catalog uses the local demo player until a licensed provider embed is connected.',
  controls: 'Keyboard / touch controls depend on the connected game.',
  embedUrl: '/demo-game.html',
  mobileSupported: true,
  desktopSupported: true,
  status: 'published',
  featured: [0,4,9,14].includes(index),
  trending: [0,2,4,13,16,25].includes(index),
  publishedAt: new Date(Date.now() - index * 86400000).toISOString(),
  createdAt: new Date(Date.now() - index * 86400000).toISOString(),
  updatedAt: new Date().toISOString(),
}));

export const seedCategories = [
  'Action','Adventure','Arcade','Board','Casual','Girls','Multiplayer','Puzzle','Racing','Shooting','Sports','2 Player'
].map((name, index) => ({
  name,
  slug: name.toLowerCase().replaceAll(' ', '-'),
  description: `Play free ${name.toLowerCase()} games instantly in your browser.`,
  enabled: true,
  sortOrder: index,
}));
