import type {Game} from './types';

export type SeoTopic={
  slug:string;
  title:string;
  h1:string;
  metaDescription:string;
  summary:string;
  categories:string[];
  terms:string[];
  mobileOnly?:boolean;
  desktopOnly?:boolean;
  searchIntent:string;
  playAdvice:string;
  compatibility:string;
};

export const seoTopics:SeoTopic[]=[
  {slug:'free-online-games-no-download',title:'Free Online Games — No Download Required',h1:'Free Online Games With No Download',metaDescription:'Play free online games with no download required. Browse instant browser games across racing, action, puzzle, sports and more on MADGAMES.FUN.',summary:'A broad instant-play collection for people who want to open a game in the browser instead of installing a separate app.',categories:[],terms:[],searchIntent:'This page is built for players searching for free games that start in a web browser. It brings the main catalog together in one place so you can compare genres before opening a title.',playAdvice:'Start with a category you already enjoy, then check the individual game page for controls and device support. Short browser sessions are easiest when you choose a title that matches the input method you have available.',compatibility:'Normal gameplay on MADGAMES.FUN is intended for browser play. Individual provider requirements can differ, so the game page remains the source of truth for mobile and desktop support.'},
  {slug:'free-browser-games',title:'Free Browser Games Online — Play Instantly',h1:'Free Browser Games Online',metaDescription:'Discover free browser games you can play online instantly. Find action, racing, puzzle, sports, casual and adventure games on MADGAMES.FUN.',summary:'An all-genre browser gaming page focused on quick discovery and instant play.',categories:[],terms:['browser'],searchIntent:'Use this collection when your main requirement is playing inside a browser rather than choosing one specific genre. The catalog mixes quick arcade-style ideas with racing, puzzles, sports and adventure titles.',playAdvice:'Open a few game pages and compare descriptions, controls and device badges before committing to a longer session. Favorites and Recent can help you return to titles you enjoyed.',compatibility:'Browser games can behave differently across devices, browsers and providers. MADGAMES.FUN lists mobile and desktop support on each game page where that information is available.'},
  {slug:'mobile-browser-games',title:'Free Mobile Browser Games — Play Online',h1:'Free Mobile Browser Games',metaDescription:'Play free mobile browser games online without a normal app download. Browse touch-friendly game listings and check mobile support before playing.',summary:'A mobile-first discovery page that prioritizes games marked as supporting mobile browsers.',categories:[],terms:['mobile','touch'],mobileOnly:true,searchIntent:'This page is for players searching from a phone or tablet who want browser-based games. Results prioritize titles that the catalog marks as mobile supported.',playAdvice:'For the smoothest session, keep your browser updated and check whether the game prefers portrait or landscape play when that information is provided. Touch controls vary by provider.',compatibility:'Only games currently marked as mobile supported are prioritized here. A provider can still have its own browser, orientation or performance requirements.'},
  {slug:'desktop-browser-games',title:'Free Desktop Browser Games — Play Online',h1:'Free Desktop Browser Games',metaDescription:'Play free desktop browser games online on MADGAMES.FUN. Browse keyboard-friendly action, racing, puzzle, sports and other web games.',summary:'A desktop-focused collection prioritizing games listed as supporting desktop browsers.',categories:[],terms:['desktop','keyboard'],desktopOnly:true,searchIntent:'This collection is aimed at laptop and desktop players who want games that open on the web. It is useful when a larger screen, keyboard or mouse is your preferred setup.',playAdvice:'Check the controls section on each game page before starting. Some games use keyboard input, some use a mouse and others depend on the embedded provider interface.',compatibility:'Results prioritize games marked as desktop supported. Exact browser, keyboard and graphics requirements can still vary from one provider to another.'},
  {slug:'two-player-games-online',title:'2 Player Games Online — Free Browser Games',h1:'2 Player Games Online',metaDescription:'Find free 2 player games online for browser play. Browse same-screen and multiplayer-style game listings on MADGAMES.FUN.',summary:'A focused collection for players looking for two-player or multiplayer-style browser games.',categories:['2 Player','Multiplayer'],terms:['duo','2 player','multiplayer'],searchIntent:'This page targets the simple question: what can two people play together in a browser? It prioritizes titles categorized as 2 Player or Multiplayer and related catalog matches.',playAdvice:'Check the game description before starting because “2 player” can mean shared-screen, turn-based or provider-hosted multiplayer. Controls and connection requirements differ by title.',compatibility:'The catalog can include both local and online multiplayer formats. The individual game page should be checked for the exact play mode and supported devices.'},
  {slug:'racing-games-online',title:'Free Racing Games Online — Play in Browser',h1:'Racing Games Online',metaDescription:'Play free racing games online in your browser. Discover cars, bikes, drifting and driving challenges on MADGAMES.FUN.',summary:'A high-intent racing collection covering driving, drifting, cars, bikes and track challenges.',categories:['Racing'],terms:['race','racing','drift'],searchIntent:'Choose this page when you want speed-focused games rather than a general catalog. It groups racing titles and closely related driving challenges into one discovery path.',playAdvice:'Racing games can reward very different skills: clean cornering, drifting, parking precision or stunt timing. Read the description first so you can pick the style you actually want.',compatibility:'Some racing games work well with touch controls while others are easier with a keyboard. Device support and controls are listed per game when available.'},
  {slug:'car-games-online',title:'Free Car Games Online — No Download',h1:'Car Games Online',metaDescription:'Play free car games online with no normal download. Find driving, parking, drifting and arcade car games in your browser.',summary:'A car-focused landing page for driving, parking, drifting and arcade vehicle games.',categories:['Racing'],terms:['car','drive','parking','drift'],searchIntent:'This collection narrows the racing catalog toward car-related searches. It is useful if you want driving, parking, drifting or vehicle-based arcade play without browsing unrelated genres.',playAdvice:'If you prefer precision, start with parking or controlled driving challenges. If you want faster sessions, look for drift, race or arcade-style descriptions.',compatibility:'Control schemes differ across car games. Check whether the selected title lists mobile, desktop or both before you begin.'},
  {slug:'driving-games-online',title:'Free Driving Games Online — Browser Play',h1:'Driving Games Online',metaDescription:'Discover free driving games online for instant browser play. Browse cars, parking, traffic and stunt-style driving games on MADGAMES.FUN.',summary:'A driving-focused collection built around steering, traffic, parking and vehicle-control gameplay.',categories:['Racing'],terms:['drive','driving','parking','rider','street'],searchIntent:'Driving-game searches are often broader than racing. This page therefore highlights vehicle control, parking, traffic and road-style gameplay alongside relevant racing titles.',playAdvice:'Pick based on the type of control challenge you want: speed, accuracy, traffic navigation or stunts. The game description and controls section can help you decide quickly.',compatibility:'Driving titles may use arrow keys, WASD, touch buttons or provider-specific controls. Confirm the listed device support on the game page.'},
  {slug:'bike-games-online',title:'Free Bike Games Online — Play Instantly',h1:'Bike Games Online',metaDescription:'Play free bike games online in your browser. Find stunt, rider and racing game listings with instant-play discovery on MADGAMES.FUN.',summary:'A bike and rider search page highlighting motorcycle, stunt and two-wheel racing matches.',categories:['Racing'],terms:['bike','bikes','rider','motorcycle'],searchIntent:'This page is for players who specifically want bike or rider gameplay instead of cars. Exact-match bike titles are shown first, followed by closely related racing options when the catalog is smaller.',playAdvice:'Bike games often emphasize balance, timing and landing as much as raw speed. Read the description to see whether a title focuses on stunts, traffic or conventional racing.',compatibility:'Touch and keyboard support varies by game. The title page indicates the device support currently stored in the catalog.'},
  {slug:'action-games-online',title:'Free Action Games Online — Play Instantly',h1:'Action Games Online',metaDescription:'Play free action games online in your browser. Discover battles, arcade action, fast challenges and combat-style games on MADGAMES.FUN.',summary:'Fast-paced browser games centered on movement, battles, reactions and arcade action.',categories:['Action'],terms:['battle','action','arena'],searchIntent:'Use this collection when you want active, reaction-heavy gameplay rather than puzzles or relaxed casual games. It prioritizes the Action category and related battle-style titles.',playAdvice:'Action games can range from quick score chases to longer combat rounds. Check controls first, especially if you are choosing between mobile touch input and desktop keyboard play.',compatibility:'Performance and input requirements depend on the embedded game provider. Mobile and desktop support are shown on the individual game page when known.'},
  {slug:'shooting-games-online',title:'Free Shooting Games Online — Browser Play',h1:'Shooting Games Online',metaDescription:'Find free shooting games online for browser play. Browse aim, sniper and arcade shooting game listings on MADGAMES.FUN.',summary:'A shooting-focused collection for aim, sniper and arcade battle searches.',categories:['Shooting','Action'],terms:['shoot','sniper','gun','aim'],searchIntent:'This page filters the broader action catalog toward shooting and aiming gameplay. Dedicated Shooting titles rank first, with clearly related action matches used to expand discovery.',playAdvice:'Look at the description to distinguish precision aiming games from faster arena-style action. Mouse, keyboard and touch controls can create very different play experiences.',compatibility:'Input support varies widely in shooting games, so checking the controls and device badges before launching is especially useful.'},
  {slug:'puzzle-games-online',title:'Free Puzzle Games Online — Play in Browser',h1:'Puzzle Games Online',metaDescription:'Play free puzzle games online in your browser. Find matching, logic, tile and brain-style games with no normal download required.',summary:'A puzzle collection for matching, logic, tiles, merging and brain-style browser games.',categories:['Puzzle'],terms:['puzzle','brain','tiles','merge','match'],searchIntent:'This collection is designed for players looking for problem-solving rather than fast action. It groups visual puzzles, matching ideas, merging mechanics and other brain-style challenges.',playAdvice:'Choose based on whether you prefer relaxed pattern recognition or a more demanding logic challenge. Short descriptions can help you avoid starting a puzzle style you do not enjoy.',compatibility:'Many puzzle games suit both touch and mouse input, but each provider is different. Check the stored mobile and desktop support for the selected title.'},
  {slug:'football-games-online',title:'Free Football Games Online — Play Instantly',h1:'Football Games Online',metaDescription:'Play free football games online in your browser. Find goal, soccer and arcade football game listings on MADGAMES.FUN.',summary:'A football-focused sports page prioritizing goal, soccer and arcade football matches.',categories:['Sports'],terms:['football','soccer','goal'],searchIntent:'This page narrows the Sports category toward football and goal-based gameplay. Exact football-style matches are prioritized before other sports titles.',playAdvice:'Browser football games can focus on shooting, timing, quick matches or simplified arcade controls. Check the game description to choose the format closest to what you want.',compatibility:'Some football games are designed for touch while others are easier on desktop. Current device support is shown per game.'},
  {slug:'cricket-games-online',title:'Free Cricket Games Online — Browser Play',h1:'Cricket Games Online',metaDescription:'Find free cricket games online for instant browser play. Browse batting, timing and sports game listings on MADGAMES.FUN.',summary:'A cricket search page prioritizing cricket titles and then closely related sports games.',categories:['Sports'],terms:['cricket','batting','bat'],searchIntent:'This collection is for players searching specifically for browser cricket. Exact cricket matches come first; additional sports titles are only used when they help keep discovery useful.',playAdvice:'Cricket browser games often simplify batting, timing or scoring into short rounds. Read the controls and description to understand the format before starting.',compatibility:'Device support depends on the game provider. Check the mobile and desktop indicators on each cricket title page.'},
  {slug:'basketball-games-online',title:'Free Basketball Games Online — Play Instantly',h1:'Basketball Games Online',metaDescription:'Play free basketball games online in your browser. Find hoops, shooting and arcade sports game listings on MADGAMES.FUN.',summary:'A basketball-focused sports collection for hoops, shooting and score-chasing searches.',categories:['Sports'],terms:['basketball','hoops','hoop'],searchIntent:'This page prioritizes basketball and hoops-style titles for players who do not want to browse the full Sports category. Related sports games appear only after the strongest matches.',playAdvice:'Many browser basketball games focus on shot timing and streaks rather than full simulations. The description will tell you whether the game is a quick scoring challenge or something broader.',compatibility:'Controls can be touch, mouse or keyboard based. Confirm device support on the game page before playing.'},
  {slug:'sports-games-online',title:'Free Sports Games Online — Play in Browser',h1:'Sports Games Online',metaDescription:'Play free sports games online in your browser. Discover football, cricket, basketball and arcade sports titles on MADGAMES.FUN.',summary:'A broad sports collection covering football, cricket, basketball and other arcade-style sports games.',categories:['Sports'],terms:['sports','goal','cricket','hoops'],searchIntent:'Use this page when you want sports games but have not chosen a specific sport yet. It keeps football, cricket, basketball and other sports-style listings together for easy comparison.',playAdvice:'Pick a sport first, then compare game descriptions to see whether the title is simulation-inspired, timing-based or purely arcade. Short sessions are often easiest with simple control schemes.',compatibility:'Sports games can support mobile, desktop or both. Exact controls and device support are shown on each game listing when known.'},
  {slug:'adventure-games-online',title:'Free Adventure Games Online — Browser Play',h1:'Adventure Games Online',metaDescription:'Play free adventure games online in your browser. Discover running, jumping, exploration and obstacle-style games on MADGAMES.FUN.',summary:'Adventure browser games built around movement, exploration, obstacles and progression.',categories:['Adventure'],terms:['adventure','island','jungle','ninja','run'],searchIntent:'This collection is for players who want movement and progression without limiting the search to pure action. It includes running, obstacle, exploration and journey-style adventure matches.',playAdvice:'Read the description to see whether the title emphasizes exploration, platform-style movement or endless running. That difference matters more than the broad Adventure label.',compatibility:'Adventure games may use touch, keyboard or mixed controls depending on the provider. Check the listed device support before launching.'},
  {slug:'running-games-online',title:'Free Running Games Online — Play Instantly',h1:'Running Games Online',metaDescription:'Play free running games online in your browser. Find dash, jump, obstacle and endless-run style game listings on MADGAMES.FUN.',summary:'A running and obstacle collection emphasizing dashes, jumps, dodging and forward-motion gameplay.',categories:['Adventure'],terms:['run','running','dash','jump','dodge'],searchIntent:'This page narrows adventure games toward running, dashing, jumping and obstacle avoidance. Exact running matches are shown before broader adventure recommendations.',playAdvice:'Running games often reward reaction timing and route awareness. Choose between endless score chasing and level-based obstacle challenges by reading the short gameplay description.',compatibility:'Fast reaction games can feel different on touch and keyboard. The game page shows the device support currently recorded for each title.'},
  {slug:'casual-games-online',title:'Free Casual Games Online — Play Instantly',h1:'Casual Games Online',metaDescription:'Play free casual games online in your browser. Discover quick, simple and relaxed browser games on MADGAMES.FUN.',summary:'Easy-to-start browser games for quick sessions, simple controls and relaxed play.',categories:['Casual'],terms:['casual','flip','candy','chef','craft'],searchIntent:'This page is for players who want something easy to start without learning a complex system. It prioritizes casual titles and simple browser-friendly game loops.',playAdvice:'Casual does not always mean effortless, but the rules are usually quick to understand. Use descriptions and controls to find a title that fits the amount of attention and time you have.',compatibility:'Many casual games are suitable for short mobile or desktop sessions, though support still depends on the individual provider.'},
  {slug:'multiplayer-browser-games',title:'Free Multiplayer Browser Games Online',h1:'Multiplayer Browser Games',metaDescription:'Find free multiplayer browser games online. Browse multiplayer and 2 player game listings for instant web-based discovery on MADGAMES.FUN.',summary:'A multiplayer-focused collection covering browser multiplayer and two-player game listings.',categories:['Multiplayer','2 Player'],terms:['multiplayer','duo','2 player','arena'],searchIntent:'Use this page when playing with or against other people matters more than the genre. It combines Multiplayer and 2 Player catalog entries while keeping each title’s exact mode visible on its game page.',playAdvice:'Before launching, confirm whether the title is local two-player, online multiplayer or simply multiplayer-style. Provider requirements and matchmaking can vary significantly.',compatibility:'Multiplayer games may require a stable connection or specific provider features. Device support and the available mode should be checked on the individual title.'}
];

export function getSeoTopic(slug:string){return seoTopics.find(topic=>topic.slug===slug)}

export function getTopicGames(topic:SeoTopic,games:Game[],limit=24){
  const categories=topic.categories.map(value=>value.toLowerCase());
  const terms=topic.terms.map(value=>value.toLowerCase());
  const eligible=games.filter(game=>(!topic.mobileOnly||game.mobileSupported)&&(!topic.desktopOnly||game.desktopSupported));
  const scored=eligible.map(game=>{
    const haystack=[game.title,game.category,...(game.categories||[]),...(game.tags||[]),game.description].join(' ').toLowerCase();
    let score=0;
    if(categories.includes(game.category.toLowerCase()))score+=5;
    if((game.categories||[]).some(category=>categories.includes(category.toLowerCase())))score+=4;
    for(const term of terms)if(haystack.includes(term))score+=3;
    if(game.trending)score+=1;
    if(game.featured)score+=1;
    return {game,score};
  });
  const relevant=scored.filter(item=>item.score>0||(!categories.length&&!terms.length)).sort((a,b)=>b.score-a.score).map(item=>item.game);
  const fallback=scored.filter(item=>!relevant.some(game=>game.id===item.game.id)).sort((a,b)=>b.score-a.score).map(item=>item.game);
  return [...relevant,...fallback].slice(0,limit);
}

export function getTopicsForCategory(category:string,limit=6){
  const key=category.toLowerCase();
  return seoTopics.filter(topic=>topic.categories.some(value=>value.toLowerCase()===key)).slice(0,limit);
}

export function getTopicFaqs(topic:SeoTopic){
  return [
    {question:`Can I play ${topic.h1.toLowerCase()} for free?`,answer:`MADGAMES.FUN lists games in this collection for free browser play. A third-party provider can still have its own terms, ads or optional in-game features.`},
    {question:`Do ${topic.h1.toLowerCase()} need a download?`,answer:'The normal experience on this site is browser-based play, so a separate game installation is not normally required. Individual provider requirements can vary.'},
    {question:`Can I play these games on mobile and desktop?`,answer:topic.compatibility}
  ];
}
